### ISSUE TITLE
spring cloud data flow server cloud foundry config server 

### ISSUE THREAD

**Issue by faissalwise** [spring-cloud/spring-cloud-dataflow-server-cloudfoundry#457] opened 2018-12-07 17:41 UTC
Hello,

I deployed spring cloud data flow server cloud foundry to PCF.When i run it it try to connect to use http://localhost:8888 config server.

I'm using my own config sever and in manifest file i'am using  services: config-service (as a user provided service).But even with this config it will try to connect http://localhost:8888.

Thanks

**Comment by sabbyanandan** [comment] 2018-12-10 15:12
Hi, @faissalwise. This appears to be a duplicate of [StackOverflow](https://stackoverflow.com/questions/53674551/spring-cloud-data-flow-server-cloud-foundry-config-server) thread. Let's follow-up there instead. cc:/ @ilayaperumalg

**Closed by sabbyanandan** 2018-12-10 15:12 UTC

**Comment by faissalwise** [comment] 2018-12-10 15:22
Hi @sabbyanandan ,Thanks for your reply.
I posted also in https://stackoverflow.com/questions/53674551/spring-cloud-data-flow-server-cloud-foundry-config-server.
