### ISSUE TITLE
Exceptions in logs when stream app is un-deployed

### ISSUE THREAD

**Issue by trisberg** [spring-cloud/spring-cloud-dataflow-server-cloudfoundry#302] opened 2017-04-05 20:20 UTC
I deployed a stream and while tailing the logs I noticed some exceptions showing up when the stream was un-deployed. This doesn't seem right, and it looks ugly:

```
2017-04-05T16:11:08.48-0400 [APP/PROC/WEB/0]OUT 2017-04-05 20:11:08.488  WARN 15 --- [-new.test-new-1] dataflow-server-test-new-log-new         : Hello there, test-app!
2017-04-05T16:16:46.07-0400 [API/4]      OUT Updated app with guid 0c77819c-12e9-4901-854e-70c1447613bf ({"service_binding"=>"b40aff69-c18b-4fac-9348-6f44f2ae0c45", :verb=>"remove", :relation=>"service_bindings", :related_guid=>"b40aff69-c18b-4fac-9348-6f44f2ae0c45"})
2017-04-05T16:16:46.39-0400 [API/3]      OUT Updated app with guid 0c77819c-12e9-4901-854e-70c1447613bf ({"service_binding"=>"43e1e3a4-5804-404b-8504-2d6d2656f4fc", :verb=>"remove", :relation=>"service_bindings", :related_guid=>"43e1e3a4-5804-404b-8504-2d6d2656f4fc"})
2017-04-05T16:16:46.44-0400 [API/3]      OUT Deleting app package for app with guid 0c77819c-12e9-4901-854e-70c1447613bf
2017-04-05T16:16:46.45-0400 [API/3]      OUT Deleting droplet for app with guid 0c77819c-12e9-4901-854e-70c1447613bf
2017-04-05T16:16:46.45-0400 [API/3]      OUT Deleting process: "web"
2017-04-05T16:16:46.54-0400 [APP/PROC/WEB/0]OUT 2017-04-05 20:16:46.540  INFO 15 --- [       Thread-6] ationConfigEmbeddedWebApplicationContext : Closing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@5891e32e: startup date [Wed Apr 05 20:09:41 UTC 2017]; parent: org.springframework.context.annotation.AnnotationConfigApplicationContext@51521cc1
2017-04-05T16:16:46.54-0400 [APP/PROC/WEB/0]OUT 2017-04-05 20:16:46.541  INFO 15 --- [       Thread-6] s.c.a.AnnotationConfigApplicationContext : Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@65fd6708: startup date [Wed Apr 05 20:09:49 UTC 2017]; parent: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@5891e32e
2017-04-05T16:16:46.54-0400 [APP/PROC/WEB/0]OUT 2017-04-05 20:16:46.542  INFO 15 --- [       Thread-6] o.s.c.support.DefaultLifecycleProcessor  : Stopping beans in phase -2147482648
2017-04-05T16:16:46.54-0400 [API/3]      OUT Deleted app with guid 0c77819c-12e9-4901-854e-70c1447613bf
2017-04-05T16:16:46.54-0400 [CELL/0]     OUT Exit status 0
2017-04-05T16:16:46.67-0400 [APP/PROC/WEB/0]OUT 2017-04-05 20:16:46.673  INFO 15 --- [       Thread-6] o.s.c.support.DefaultLifecycleProcessor  : Stopping beans in phase 2147483647
2017-04-05T16:16:46.67-0400 [APP/PROC/WEB/0]OUT 2017-04-05 20:16:46.674  INFO 15 --- [       Thread-6] o.s.c.support.DefaultLifecycleProcessor  : Stopping beans in phase 2147482647
2017-04-05T16:16:46.68-0400 [APP/PROC/WEB/0]OUT 	at org.springframework.cloud.stream.binding.BindingService.unbindConsumers(BindingService.java:135) ~[spring-cloud-stream-1.2.1.BUILD-SNAPSHOT.jar!/:1.2.1.BUILD-SNAPSHOT]
2017-04-05T16:16:46.68-0400 [APP/PROC/WEB/0]OUT 	at org.springframework.cloud.stream.binding.InputBindingLifecycle.stop(InputBindingLifecycle.java:77) ~[spring-cloud-stream-1.2.1.BUILD-SNAPSHOT.jar!/:1.2.1.BUILD-SNAPSHOT]
2017-04-05T16:16:46.68-0400 [APP/PROC/WEB/0]OUT 2017-04-05 20:16:46.685  WARN 15 --- [       Thread-6] o.s.c.support.DefaultLifecycleProcessor  : Failed to stop bean 'inputBindingLifecycle'
2017-04-05T16:16:46.68-0400 [APP/PROC/WEB/0]OUT org.springframework.amqp.UncategorizedAmqpException: java.lang.IllegalStateException: The ApplicationContext is closed and the ConnectionFactory can no longer create connections.
2017-04-05T16:16:46.68-0400 [APP/PROC/WEB/0]OUT 	at org.springframework.amqp.rabbit.support.RabbitExceptionTranslator.convertRabbitAccessException(RabbitExceptionTranslator.java:83) ~[spring-rabbit-1.7.1.RELEASE.jar!/:na]
2017-04-05T16:16:46.68-0400 [APP/PROC/WEB/0]OUT 	at org.springframework.amqp.rabbit.connection.RabbitAccessor.convertRabbitAccessException(RabbitAccessor.java:113) ~[spring-rabbit-1.7.1.RELEASE.jar!/:na]
2017-04-05T16:16:46.68-0400 [APP/PROC/WEB/0]OUT 	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.doStop(SimpleMessageListenerContainer.java:854) ~[spring-rabbit-1.7.1.RELEASE.jar!/:na]
2017-04-05T16:16:46.68-0400 [APP/PROC/WEB/0]OUT 	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.stop(AbstractMessageListenerContainer.java:580) ~[spring-rabbit-1.7.1.RELEASE.jar!/:na]
2017-04-05T16:16:46.68-0400 [APP/PROC/WEB/0]OUT 	at org.springframework.cloud.stream.binder.DefaultBinding.unbind(DefaultBinding.java:71) ~[spring-cloud-stream-1.2.1.BUILD-SNAPSHOT.jar!/:1.2.1.BUILD-SNAPSHOT]
2017-04-05T16:16:46.68-0400 [APP/PROC/WEB/0]OUT 	at org.springframework.cloud.stream.binding.BindableProxyFactory.unbindInputs(BindableProxyFactory.java:254) ~[spring-cloud-stream-1.2.1.BUILD-SNAPSHOT.jar!/:1.2.1.BUILD-SNAPSHOT]
2017-04-05T16:16:46.68-0400 [APP/PROC/WEB/0]OUT 	at org.springframework.context.support.DefaultLifecycleProcessor.doStop(DefaultLifecycleProcessor.java:231) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
2017-04-05T16:16:46.68-0400 [APP/PROC/WEB/0]OUT 	at org.springframework.context.support.DefaultLifecycleProcessor.access$300(DefaultLifecycleProcessor.java:50) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
2017-04-05T16:16:46.68-0400 [APP/PROC/WEB/0]OUT 	at org.springframework.context.support.DefaultLifecycleProcessor.stopBeans(DefaultLifecycleProcessor.java:204) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
2017-04-05T16:16:46.68-0400 [APP/PROC/WEB/0]OUT 	at org.springframework.context.support.DefaultLifecycleProcessor.onClose(DefaultLifecycleProcessor.java:120) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
2017-04-05T16:16:46.68-0400 [APP/PROC/WEB/0]OUT 	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1002) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
2017-04-05T16:16:46.68-0400 [APP/PROC/WEB/0]OUT 	at org.springframework.context.support.AbstractApplicationContext$2.run(AbstractApplicationContext.java:928) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
2017-04-05T16:16:46.68-0400 [APP/PROC/WEB/0]OUT Caused by: java.lang.IllegalStateException: The ApplicationContext is closed and the ConnectionFactory can no longer create connections.
2017-04-05T16:16:46.68-0400 [APP/PROC/WEB/0]OUT 	at org.springframework.util.Assert.state(Assert.java:70) ~[spring-core-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
2017-04-05T16:16:46.68-0400 [APP/PROC/WEB/0]OUT 	at org.springframework.amqp.rabbit.connection.CachingConnectionFactory.createConnection(CachingConnectionFactory.java:561) ~[spring-rabbit-1.7.1.RELEASE.jar!/:na]
2017-04-05T16:16:46.68-0400 [APP/PROC/WEB/0]OUT 	at org.springframework.amqp.rabbit.connection.CachingConnectionFactory.createBareChannel(CachingConnectionFactory.java:518) ~[spring-rabbit-1.7.1.RELEASE.jar!/:na]
2017-04-05T16:16:46.68-0400 [APP/PROC/WEB/0]OUT 	at org.springframework.amqp.rabbit.connection.CachingConnectionFactory.access$500(CachingConnectionFactory.java:98) ~[spring-rabbit-1.7.1.RELEASE.jar!/:na]
2017-04-05T16:16:46.68-0400 [APP/PROC/WEB/0]OUT 	at org.springframework.amqp.rabbit.connection.CachingConnectionFactory$CachedChannelInvocationHandler.invoke(CachingConnectionFactory.java:953) ~[spring-rabbit-1.7.1.RELEASE.jar!/:na]
2017-04-05T16:16:46.68-0400 [APP/PROC/WEB/0]OUT 	at com.sun.proxy.$Proxy127.basicCancel(Unknown Source) ~[na:na]
2017-04-05T16:16:46.68-0400 [APP/PROC/WEB/0]OUT 	at org.springframework.amqp.rabbit.listener.BlockingQueueConsumer.basicCancel(BlockingQueueConsumer.java:347) ~[spring-rabbit-1.7.1.RELEASE.jar!/:na]
2017-04-05T16:16:46.68-0400 [APP/PROC/WEB/0]OUT 	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.shutdown(AbstractMessageListenerContainer.java:493) ~[spring-rabbit-1.7.1.RELEASE.jar!/:na]
2017-04-05T16:16:46.68-0400 [APP/PROC/WEB/0]OUT 	... 16 common frames omitted
2017-04-05T16:16:46.68-0400 [APP/PROC/WEB/0]OUT 	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.shutdown(AbstractMessageListenerContainer.java:496) ~[spring-rabbit-1.7.1.RELEASE.jar!/:na]
2017-04-05T16:16:46.68-0400 [APP/PROC/WEB/0]OUT 	at org.springframework.integration.amqp.inbound.AmqpInboundChannelAdapter.doStop(AmqpInboundChannelAdapter.java:110) ~[spring-integration-amqp-4.3.8.RELEASE.jar!/:4.3.8.RELEASE]
2017-04-05T16:16:46.68-0400 [APP/PROC/WEB/0]OUT 	at org.springframework.integration.endpoint.AbstractEndpoint.stop(AbstractEndpoint.java:111) ~[spring-integration-core-4.3.8.RELEASE.jar!/:4.3.8.RELEASE]
2017-04-05T16:16:46.68-0400 [APP/PROC/WEB/0]OUT 	at org.springframework.cloud.stream.binding.InputBindingLifecycle.stop(InputBindingLifecycle.java:100) ~[spring-cloud-stream-1.2.1.BUILD-SNAPSHOT.jar!/:1.2.1.BUILD-SNAPSHOT]
2017-04-05T16:16:46.68-0400 [APP/PROC/WEB/0]OUT 	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.stop(DefaultLifecycleProcessor.java:365) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
2017-04-05T16:16:46.68-0400 [APP/PROC/WEB/0]OUT 	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.doShutdown(SimpleMessageListenerContainer.java:871) ~[spring-rabbit-1.7.1.RELEASE.jar!/:na]
2017-04-05T16:16:56.55-0400 [APP/PROC/WEB/0]OUT Exit status 137
2017-04-05T16:16:56.56-0400 [CELL/0]     OUT Destroying container
2017-04-05T16:16:57.12-0400 [CELL/0]     OUT Successfully destroyed container
```

**Comment by markpollack** [comment] 2017-04-06 15:57
This looks to be an issue in the deployer, we do not request to stop the application before deleting it.  Will test again as part of fixing https://github.com/spring-cloud/spring-cloud-deployer-cloudfoundry/issues/171

**Comment by ilayaperumalg** [comment] 2017-04-17 04:14
Tried with the latest SCDF CF and I don't seem to find any exception messages reported in this issue. 

Stream (with apps from Avogadro and Bacon latest) undeployment went successful with the following messages:

```
2017-04-17T09:19:25.75+0530 [APP/PROC/WEB/0]OUT 2017-04-17 03:49:25.752  INFO 20 --- [ry-client-nio-6] o.s.c.d.s.c.CloudFoundryAppDeployer      : Successfully undeployed app ilaya-test-m1fCdin-a1-time
2017-04-17T09:19:27.09+0530 [APP/PROC/WEB/0]OUT 2017-04-17 03:49:27.098  INFO 20 --- [ry-client-nio-4] o.s.c.d.s.c.CloudFoundryAppDeployer      : Successfully undeployed app ilaya-test-m1fCdin-a1-log
```

**Comment by markpollack** [comment] 2017-04-17 15:18
The PR for this is here - https://github.com/spring-cloud/spring-cloud-deployer-cloudfoundry/pull/172

**Comment by markpollack** [comment] 2017-04-19 20:02
I was able to reproduce it on PWS, along with thomas and Sabby. Not sure why you didn't see it.

I tried adding a request to stop

```
	public void undeploy(String id) {
		getStatus(id)
			.doOnNext(status -> assertApplicationExists(id, status))
				// Need to block here to be able to throw exception early
			.block(Duration.ofSeconds(this.deploymentProperties.getApiTimeout()));
		requestStopApplication(id)
			.doOnSuccess(v -> logger.info("Successfully stopped app {}", id))
			.doOnError(logError(String.format("Failed to stop app %s", id)))
			.block(Duration.ofSeconds(this.deploymentProperties.getApiTimeout()));
		requestDeleteApplication(id)
			.timeout(Duration.ofSeconds(this.deploymentProperties.getApiTimeout()))
			.doOnSuccess(v -> logger.info("Successfully undeployed app {}", id))
			.doOnError(logError(String.format("Failed to undeploy app %s", id)))
			.subscribe();
	}
```

but that didn't solve the issue.  I think the core issue is that services are unbound and then there is a call to delete the app in the cf-java-client library.  Will inquire about that....

**Comment by nebhale** [comment] 2017-04-19 20:26
A couple things to know about this:

1.  Bound services are only environment variables in the container
1. Unbinding (or binding) a service, doesn't change the environment in a running container, a restart (really anything that causes a new container to come into existence) is the only way to change the environment
1. Unbinding a service will only influence a live connection to that service if the Service Broker wants it to. You could imagine unbinding a service from a database removes the unique user created for that service binding.  I have *never* seen this before; credentials are almost exclusively managed so that they're scoped to service instances, not service bindings.

Looking over the logs, specifically:

```
o.s.c.support.DefaultLifecycleProcessor  : Failed to stop bean 'inputBindingLifecycle'
org.springframework.amqp.UncategorizedAmqpException: java.lang.IllegalStateException: The ApplicationContext is closed and the ConnectionFactory can no longer create connections.
  at org.springframework.amqp.rabbit.support.RabbitExceptionTranslator.convertRabbitAccessException(RabbitExceptionTranslator.java:83) ~[spring-rabbit-1.7.1.RELEASE.jar!/:na]
  at org.springframework.amqp.rabbit.connection.RabbitAccessor.convertRabbitAccessException(RabbitAccessor.java:113) ~[spring-rabbit-1.7.1.RELEASE.jar!/:na]
  at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.doStop(SimpleMessageListenerContainer.java:854) ~[spring-rabbit-1.7.1.RELEASE.jar!/:na]
..
Caused by: java.lang.IllegalStateException: The ApplicationContext is closed and the ConnectionFactory can no longer create connections.
  at org.springframework.util.Assert.state(Assert.java:70) ~[spring-core-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
  at org.springframework.amqp.rabbit.connection.CachingConnectionFactory.createConnection(CachingConnectionFactory.java:561) ~[spring-rabbit-1.7.1.RELEASE.jar!/:na]
```

this looks like the `ApplicationContext` is shutting down and one of the beans attempts to do it's shutdown *after* the `ConnectionFactory` has already closed down.  Tying that in with the logs:

```
o.s.c.support.DefaultLifecycleProcessor  : Stopping beans in phase -2147482648
o.s.c.support.DefaultLifecycleProcessor  : Stopping beans in phase 2147483647
```

it might indicate that all of the beans are `@Ordered` to be lowest priority and then it's a random chance the order that the `inputBindingLifecycle` and the `connectionFactory` get shut down in (possibly accounting for @ilayaperumalg's lack of reproduction).

This doesn't look like a CF issue so much as the `ConnectionFactory` has shutdown cleaning in the JVM and then something else calls it.

**Comment by garyrussell** [comment] 2017-04-20 14:01
A couple of observations:

1. We only emit this `The ApplicationContext is closed and the ConnectionFactory can no longer create connections.` after the context that declared.
2. We are stopping the listener container (presumably in a different context because of 1).
3. We should fix Spring AMQP to not attempt to `basicCancel` a channel if the channel is already closed (there's no point - and that's a bug).

So, we can avoid the stacktrace with a fix in Spring AMQP, but we should get to the bottom of why a container is being stopped after the context that owns its connection factory is already stopped.

**Comment by garyrussell** [comment] 2017-04-20 14:28
https://jira.spring.io/browse/AMQP-737

**Comment by mbogoevici** [comment] 2017-04-20 17:41
Thanks @nebhale and @garyrussell - looks like this can be traced down to an issue in the Rabbit binder - https://github.com/spring-cloud/spring-cloud-stream-binder-rabbit/issues/63.

**Comment by mbogoevici** [comment] 2017-04-20 19:14
Closing this as it needs to be solved via SCSt/app starter upgrades.

**Closed by mbogoevici** 2017-04-20 19:14 UTC
Labels: question, wontfix
