### ISSUE TITLE
Getting KeeperException$AuthFailedException while connecting Kerberised kafka from Spring Cloud Datalfow stream

### ISSUE THREAD

**Issue by sandip0018** [spring-cloud/spring-cloud-dataflow-server-cloudfoundry#364] opened 2017-11-13 09:19 UTC
Hi @sabbyanandan,

We have created configurable custom kafka source module with 0.9 api for creating stream, which will fetch messages from kerberos enabled kafka server, and we are using high level api for doing that, we have also zookeepers.

First time module is able to fetch messages, but after 2 days, module stop fetching messages and throwing below error, we have also added retry logic and scheduler to get kerberos token every 10 minute but still same error we are getting.

```
2017-11-13T12:53:11.894+05:30 [APP/PROC/WEB/0] [OUT] 2017-11-13 07:23:11.894 INFO 14 --- [r-finder-thread] kafka.consumer.ConsumerFetcherManager : [ConsumerFetcherManager-1510235233659] Added fetcher for partitions ArrayBuffer()
2017-11-13T12:53:11.894+05:30 [APP/PROC/WEB/0] [OUT] ... 7 common frames omitted
2017-11-13T12:53:12.094+05:30 [APP/PROC/WEB/0] [OUT] 2017-11-13 07:23:12.094 WARN 14 --- [r-finder-thread] onsumerFetcherManager$LeaderFinderThread : [dart.clean.sef.comcast.fcs.mismatch-req-grp2-stg2_6785d089-e0f6-4b56-428b-b197eaf76dc6-1510235233175-d5845b38-leader-finder-thread], Failed to find leader for Set([dart.clean.sef.comcast.fcs.dart-mismatch-req-stg,1], [dart.clean.sef.comcast.fcs.dart-mismatch-req-stg,2], [dart.clean.sef.comcast.fcs.dart-mismatch-req-stg,0], [dart.clean.sef.comcast.fcs.dart-mismatch-req-stg,3])
2017-11-13T12:53:12.094+05:30 [APP/PROC/WEB/0] [OUT] org.I0Itec.zkclient.exception.ZkException: org.apache.zookeeper.KeeperException$AuthFailedException: KeeperErrorCode = AuthFailed for /brokers/ids
2017-11-13T12:53:12.094+05:30 [APP/PROC/WEB/0] [OUT] at org.I0Itec.zkclient.exception.ZkException.create(ZkException.java:68) ~[zkclient-0.7.jar!/:0.7]
2017-11-13T12:53:12.094+05:30 [APP/PROC/WEB/0] [OUT] at org.I0Itec.zkclient.ZkClient.getChildren(ZkClient.java:671) ~[zkclient-0.7.jar!/:0.7]
2017-11-13T12:53:12.094+05:30 [APP/PROC/WEB/0] [OUT] at kafka.utils.ZkUtils.getChildrenParentMayNotExist(ZkUtils.scala:544) ~[kafka_2.10-0.9.0.2.4.3.2-1.jar!/:na]
2017-11-13T12:53:12.094+05:30 [APP/PROC/WEB/0] [OUT] at kafka.utils.ZkUtils.getAllBrokerEndPointsForChannel(ZkUtils.scala:180) ~[kafka_2.10-0.9.0.2.4.3.2-1.jar!/:na]
2017-11-13T12:53:12.094+05:30 [APP/PROC/WEB/0] [OUT] at org.I0Itec.zkclient.ZkClient.retryUntilConnected(ZkClient.java:995) ~[zkclient-0.7.jar!/:0.7]
2017-11-13T12:53:12.094+05:30 [APP/PROC/WEB/0] [OUT] at org.I0Itec.zkclient.ZkClient.getChildren(ZkClient.java:675) ~[zkclient-0.7.jar!/:0.7]
2017-11-13T12:53:12.094+05:30 [APP/PROC/WEB/0] [OUT] at kafka.utils.ZkUtils.getAllBrokersInCluster(ZkUtils.scala:175) ~[kafka_2.10-0.9.0.2.4.3.2-1.jar!/:na]
2017-11-13T12:53:12.094+05:30 [APP/PROC/WEB/0] [OUT] at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:63) [kafka_2.10-0.9.0.2.4.3.2-1.jar!/:na]
2017-11-13T12:53:12.094+05:30 [APP/PROC/WEB/0] [OUT] at kafka.consumer.ConsumerFetcherManager$LeaderFinderThread.doWork(ConsumerFetcherManager.scala:66) ~[kafka_2.10-0.9.0.2.4.3.2-1.jar!/:na]
2017-11-13T12:53:12.094+05:30 [APP/PROC/WEB/0] [OUT] at org.apache.zookeeper.ZooKeeper.getChildren(ZooKeeper.java:1472) ~[zookeeper-3.4.6.jar!/:3.4.6-1569965]
2017-11-13T12:53:12.094+05:30 [APP/PROC/WEB/0] [OUT] at org.apache.zookeeper.KeeperException.create(KeeperException.java:123) ~[zookeeper-3.4.6.jar!/:3.4.6-1569965]
2017-11-13T12:53:12.094+05:30 [APP/PROC/WEB/0] [OUT] at org.apache.zookeeper.KeeperException.create(KeeperException.java:51) ~[zookeeper-3.4.6.jar!/:3.4.6-1569965]
2017-11-13T12:53:12.094+05:30 [APP/PROC/WEB/0] [OUT] at org.I0Itec.zkclient.ZkConnection.getChildren(ZkConnection.java:114) ~[zkclient-0.7.jar!/:0.7]
2017-11-13T12:53:12.094+05:30 [APP/PROC/WEB/0] [OUT] at org.apache.zookeeper.ZooKeeper.getChildren(ZooKeeper.java:1500) ~[zookeeper-3.4.6.jar!/:3.4.6-1569965]
2017-11-13T12:53:12.094+05:30 [APP/PROC/WEB/0] [OUT] at org.I0Itec.zkclient.ZkClient$4.call(ZkClient.java:678) ~[zkclient-0.7.jar!/:0.7]
2017-11-13T12:53:12.094+05:30 [APP/PROC/WEB/0] [OUT] Caused by: org.apache.zookeeper.KeeperException$AuthFailedException: KeeperErrorCode = AuthFailed for /brokers/ids
2017-11-13T12:53:12.094+05:30 [APP/PROC/WEB/0] [OUT] at org.I0Itec.zkclient.ZkClient$4.call(ZkClient.java:675) ~[zkclient-0.7.jar!/:0.7]
2017-11-13T12:53:12.094+05:30 [APP/PROC/WEB/0] [OUT] at org.I0Itec.zkclient.ZkClient.retryUntilConnected(ZkClient.java:985) ~[zkclient-0.7.jar!/:0.7]
2017-11-13T12:53:12.094+05:30 [APP/PROC/WEB/0] [OUT] ... 7 common frames omitted
2017-11-13T12:53:12.094+05:30 [APP/PROC/WEB/0] [OUT] 2017-11-13 07:23:12.094 INFO 14 --- [r-finder-thread] kafka.consumer.ConsumerFetcherManager : [ConsumerFetcherManager-1510235233659] Added fetcher for partitions ArrayBuffer()
2017-11-13T12:53:12.295+05:30 [APP/PROC/WEB/0] [OUT] at org.I0Itec.zkclient.exception.ZkException.create(ZkException.java:68) ~[zkclient-0.7.jar!/:0.7]
2017-11-13T12:53:12.295+05:30 [APP/PROC/WEB/0] [OUT] org.I0Itec.zkclient.exception.ZkException: org.apache.zookeeper.KeeperException$AuthFailedException: KeeperErrorCode = AuthFailed for /brokers/ids
2017-11-13T12:53:12.295+05:30 [APP/PROC/WEB/0] [OUT] at org.I0Itec.zkclient.ZkClient.retryUntilConnected(ZkClient.java:995) ~[zkclient-0.7.jar!/:0.7]
2017-11-13T12:53:12.295+05:30 [APP/PROC/WEB/0] [OUT] at org.I0Itec.zkclient.ZkClient.getChildren(ZkClient.java:675) ~[zkclient-0.7.jar!/:0.7]
2017-11-13T12:53:12.295+05:30 [APP/PROC/WEB/0] [OUT] at org.apache.zookeeper.KeeperException.create(KeeperException.java:123) ~[zookeeper-3.4.6.jar!/:3.4.6-1569965]
2017-11-13T12:53:12.295+05:30 [APP/PROC/WEB/0] [OUT] Caused by: org.apache.zookeeper.KeeperException$AuthFailedException: KeeperErrorCode = AuthFailed for /brokers/ids
2017-11-13T12:53:12.295+05:30 [APP/PROC/WEB/0] [OUT] at org.I0Itec.zkclient.ZkClient.getChildren(ZkClient.java:671) ~[zkclient-0.7.jar!/:0.7]
2017-11-13T12:53:12.295+05:30 [APP/PROC/WEB/0] [OUT] at kafka.utils.ZkUtils.getAllBrokersInCluster(ZkUtils.scala:175) ~[kafka_2.10-0.9.0.2.4.3.2-1.jar!/:na]
2017-11-13T12:53:12.295+05:30 [APP/PROC/WEB/0] [OUT] at kafka.utils.ZkUtils.getChildrenParentMayNotExist(ZkUtils.scala:544) ~[kafka_2.10-0.9.0.2.4.3.2-1.jar!/:na]
2017-11-13T12:53:12.295+05:30 [APP/PROC/WEB/0] [OUT] at kafka.utils.ZkUtils.getAllBrokerEndPointsForChannel(ZkUtils.scala:180) ~[kafka_2.10-0.9.0.2.4.3.2-1.jar!/:na]
2017-11-13T12:53:12.295+05:30 [APP/PROC/WEB/0] [OUT] at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:63) [kafka_2.10-0.9.0.2.4.3.2-1.jar!/:na]
2017-11-13T12:53:12.295+05:30 [APP/PROC/WEB/0] [OUT] at org.apache.zookeeper.KeeperException.create(KeeperException.java:51) ~[zookeeper-3.4.6.jar!/:3.4.6-1569965]
2017-11-13T12:53:12.295+05:30 [APP/PROC/WEB/0] [OUT] at org.apache.zookeeper.ZooKeeper.getChildren(ZooKeeper.java:1472) ~[zookeeper-3.4.6.jar!/:3.4.6-1569965]
2017-11-13T12:53:12.295+05:30 [APP/PROC/WEB/0] [OUT] at org.I0Itec.zkclient.ZkClient$4.call(ZkClient.java:675) ~[zkclient-0.7.jar!/:0.7]
2017-11-13T12:53:12.295+05:30 [APP/PROC/WEB/0] [OUT] at org.apache.zookeeper.ZooKeeper.getChildren(ZooKeeper.java:1500) ~[zookeeper-3.4.6.jar!/:3.4.6-1569965]
2017-11-13T12:53:12.295+05:30 [APP/PROC/WEB/0] [OUT] at org.I0Itec.zkclient.ZkConnection.getChildren(ZkConnection.java:114) ~[zkclient-0.7.jar!/:0.7]
2017-11-13T12:53:12.295+05:30 [APP/PROC/WEB/0] [OUT] at org.I0Itec.zkclient.ZkClient$4.call(ZkClient.java:678) ~[zkclient-0.7.jar!/:0.7]
2017-11-13T12:53:12.295+05:30 [APP/PROC/WEB/0] [OUT] ... 7 common frames omitted
```

Can you please help us here?,

Let me know if more information needed.

Thanks,
Sandip

**Comment by sabbyanandan** [comment] 2017-11-13 13:41
Hi, @sandip0018. At this point, it'd be best if you can share a trimmed version of the custom app that reproduces this problem. It is hard to troubleshoot just with the stacktrace, so more details about Spring Cloud Stream, Kafka, and PCF including the versions in use would be helpful as well.

**Comment by sandip0018** [comment] 2017-11-13 14:39
Hi @sabbyanandan,

Please find the below details,

Spring Cloud Stream: 1.0.0.BUILD-SNAPSHOT
Kafka: 0.9.0.2.4.3.2-1


```
@SpringBootApplication
@EnableBinding(Source.class)
public class XccKafkaApplication {
    public static void main(String args[]) {
        ShellCommandsUtil shellCommandsUtil = new ShellCommandsUtil();
    	shellCommandsUtil.runCommand("cp path/krb5.conf /home/vcap/app/.java-buildpack/open_jdk_jre/lib/security/");
/*    	
    	 try {
      	   String jaasConfigFilePath ="/home/vcap/app/ebdpdartp_kafka_jaas.conf";
      	   System.setProperty("java.security.auth.login.config", jaasConfigFilePath);
      	} catch (Exception e) {
      		e.printStackTrace();
      	}*/
    	SpringApplication.run(XccKafkaApplication.class, args);
    }

    @Autowired
    KafkaReaderOldAPI kafkaReader;

    @Bean
    public CommandLineRunner commandLineRunner() {

        return args -> kafkaReader.startKafkaReader();
    }
}
```

```
@Component
@EnableConfigurationProperties(value = KafkaSourceProperties.class)
@EnableScheduling
public class KafkaReaderOldAPI {
    private static final Logger logger = LoggerFactory.getLogger(KafkaReaderOldAPI.class);

    private Source source;
    @Autowired
    private KafkaSourceProperties config;
    private ExecutorService executor = Executors.newCachedThreadPool();

    @Autowired
    public KafkaReaderOldAPI(Source source) {
        this.source = source;
    }

    public void startKafkaReader() {
        try {
            logger.info("KafkaReader external Properties: {}", config);

            Properties props = new Properties();
            getKerberosLoginDetails();
            this.config.getKafka().forEach((k, v) -> props.put(k, v));
            getKerberosLoginDetails();
            props.setProperty("security.protocol", "PLAINTEXTSASL");

            logger.info("Creating ConsumerConfig & ConsumerConnector");
            ConsumerConfig consumerConfig = new ConsumerConfig(props);
            logger.info("ConsumerConfig created");
            ConsumerConnector consumer = kafka.consumer.Consumer.createJavaConsumerConnector(consumerConfig);
            logger.info("ConsumerConnector created");

            logger.info("Creating topicCountMap");
            Map<String, Integer> topicCountMap = new HashMap<>();
            for (String topic : config.getTopics()) {
                topicCountMap.put(topic, new Integer(1));
            }
            logger.info("topicCountMap created: {}", topicCountMap);
            logger.info("Creating consumerMap");
            Map<String, List<KafkaStream<byte[], byte[]>>> consumerMap = consumer.createMessageStreams(topicCountMap);
            logger.info("consumerMap created");

            logger.info("iterating over topics: {}", config.getTopics());

            logger.info("Creating ListeningExecutorService");
            ExecutorService executorService = Executors.newCachedThreadPool();
            ListeningExecutorService listeningExecutorService = MoreExecutors.listeningDecorator(executorService);

            List<ListenableFuture<Integer>> listenableFutures = new ArrayList<>();
            logger.info("ListeningExecutorService created");

            for (int i = 0; i < config.getTopics().size(); i++) {
                int threadNumber = 0;
                logger.info("topic: {}", config.getTopics().get(i));
                List<KafkaStream<byte[], byte[]>> streams = consumerMap.get(config.getTopics().get(i));
                logger.info("Iterating over kafkaStream from consumerMap: {}", streams.size());
                for (final KafkaStream<byte[], byte[]> stream : streams) {
                    logger.info("Creating ConsumerLoopOldApi and going to start in executor");
                    ConsumerLoopOldAPI consumerLoop = new ConsumerLoopOldAPI(threadNumber, config, source, stream, threadNumber);
                    listenableFutures.add(listeningExecutorService.submit(consumerLoop));
                    logger.info("Stream submitted: {}", threadNumber);
                    threadNumber++;
                }
            }


            final List<Integer> integers = new ArrayList<>();
            for (ListenableFuture<Integer> listenableFuture : listenableFutures) {
                logger.info("Iterating over futures to add callbacks");
                Futures.addCallback(listenableFuture, new FutureCallback<Integer>() {
                    public void onSuccess(Integer explosion) {
                        logger.info("Success, this shoud never print as we are going to continuously listen");
                    }
                    public void onFailure(Throwable thrown) {
                        logger.info("Job failed: {}", thrown.getMessage());
                        integers.add(1);
                        logger.info("Shutting down the executorService");
                        listeningExecutorService.shutdown();
                        logger.info("Shut downed executorService");
                    }
                }, executorService);
            }

            logger.info("All jobs are submitted, now lets wait for error if any");
            try {
                listeningExecutorService.awaitTermination(Long.MAX_VALUE, TimeUnit.NANOSECONDS);
                logger.info("All completed, error or success depends on size: {} ", integers.size());
                if (!integers.isEmpty()) {
                    logger.info("failed, going to restart whole process");
                    startKafkaReader();
                }
            } catch (InterruptedException e) {
                logger.info("InterruptedException in awaitTermination: {}", e.getMessage());
                e.printStackTrace();
            }
        } catch (Exception e) {
            logger.info("Exception in startKafkaReader: {}", e.getMessage());
            startKafkaReader();
        }
    }


    private void getKerberosLoginDetails() {

        logger.info("Getting Kerberos Details###########");
        try {
            String jaasConfigFilePath = config.getKerberos().get("java.security.auth.login.config");
            System.err.println("jaasConfigFilePath===" + jaasConfigFilePath);
            System.setProperty("java.security.auth.login.config", jaasConfigFilePath);
        } catch (Exception e) {
            e.printStackTrace();
        }
        org.apache.hadoop.conf.Configuration conf = new org.apache.hadoop.conf.Configuration();
        conf.set("hadoop.security.authentication", config.getKerberos().get("hadoop.security.authentication"));
        UserGroupInformation.setConfiguration(conf);
        try {
            UserGroupInformation.loginUserFromKeytab(config.getKerberos().get("userName"), new ClassPathResource(config.getKerberos().get("keytab")).getURI().toString());
            UserGroupInformation ugi = UserGroupInformation.getCurrentUser();
            UserGroupInformation.isLoginTicketBased();
            logger.info("Suceessfully loaded User Info using Kerberos");
        } catch (IOException excpetion) {
            excpetion.printStackTrace();
            logger.error("Exception occured while calling method getKerberosLoginDetails....-{}", excpetion.getMessage());
        }
    }

    @Scheduled(cron = "0 0/10 * * * *")
    public void regenerateToken() {
        logger.info("Trying to relogin in kerberose after 10 minute");
        this.getKerberosLoginDetails();
    }
}
```

```
public class ConsumerLoopOldAPI implements Callable<Integer> {

    private static final Logger logger = LoggerFactory.getLogger(ConsumerLoopOldAPI.class);
    private KafkaSourceProperties config;
    private final int id;
    private Source source;
    private final int threadNumber;
    private KafkaStream stream;
    public ConsumerLoopOldAPI(int id, KafkaSourceProperties config, Source source,KafkaStream a_stream, int a_threadNumber) {
        logger.info("Thread-ID: {} -- config: {}", id, config);
        this.id = id;
        this.config = config;
        this.source = source;
        this.stream = a_stream;
        this.threadNumber = a_threadNumber;
        Properties props = new Properties();
        this.config.getKafka().forEach((k,v) -> props.put(k, v));
        logger.info("Thread-ID: {} -- Property: {}", this.id, props);
    }

    @Override
    public Integer call() throws Exception {
        logger.info("Thread-ID: {} -- Running", this.id);
        logger.info("Thread-ID: {} -- subscribing to----------------------------->: {}", this.id, config.getTopics());

        logger.info("Thread-ID: {} -- subscribed to----------------------------->: {}", this.id, config.getTopics().get(this.id));
        ConsumerIterator<byte[], byte[]> it = stream.iterator();
        while (it.hasNext()) {
            String message = new String(it.next().message());
            logger.info("Message Received...........:{}", message);
            this.source.output().send(MessageBuilder.withPayload(message).build());
            logger.info("Sent outside for processing to next module");
        }
        return 0;
    }


  

	public void shutdown() {
      //  consumer.wakeup();
    }
}
```

```
spring:
 profiles:
  active: local
---
spring:
  profiles: local
xcc:
 topics: local.test
 kafka:
  bootstrap.servers: localhost:9092
  zookeeper.connect: localhost:2181
  group.id: grp-local-test
  serializer.class: org.apache.kafka.common.serialization.StringSerializer
  key.serializer: org.apache.kafka.common.serialization.StringSerializer
  value.serializer: org.apache.kafka.common.serialization.StringSerializer
  key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
  value.deserializer: org.apache.kafka.common.serialization.StringDeserializer
  request.required.acks: 1
  security.protocol: PLAINTEXTSASL
  sasl.mechanism: GSSAPI

 kerberos:
  hadoop.security.authentication: Kerberos
  userName: xyz@domain.COM
  keytab: xyz.keytab
  java.security.auth.login.config: xyz_kafka_jaas.conf
```

```
KafkaClient {
 com.sun.security.auth.module.Krb5LoginModule required
 doNotPrompt=true
 useTicketCache=true
 principal="xyz@domain.COM"
 useKeyTab=true
 serviceName="kafka"
 keyTab=xyz.keytab"
 client=true;
};
Client {
   com.sun.security.auth.module.Krb5LoginModule required
   useTicketCache=true
   renewTicket=true
   serviceName="zookeeper";
};
```

Let me know in case of more information needed.

Thanks,
Sandip

**Comment by sabbyanandan** [comment] 2017-11-13 17:01
Thanks for the details. I was unable to proceed after seeing: "Spring Cloud Stream: 1.0.0.BUILD-SNAPSHOT". 

I wanted to point out that this release is >1.5yrs old and we aren't actively maintaining it anymore. Since the 1.0 GA release, we have delivered three new release-trains (1.1.x, 1.2.x, and 1.3.x). Also, the Kafka client support has evolved significantly since the 1.0 release, too. More specifically, we have added and tested support for Kerberos in the 1.1 release line - here are the [PRs for review](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/pulls?q=is%3Apr+kerberos+is%3Aclosed). 

I'd highly recommend that you switch to the latest 1.3.0 / Ditmars GA release. However, if upgrading Kafka (from 0.9) is not an option, perhaps you could at least switch over to [Spring Cloud Stream 1.2.2 / Chelsea.SR2](https://docs.spring.io/spring-cloud-stream/docs/Chelsea.SR2/reference/htmlsingle/index.html), which is the last release-train to support Kafka 0.9 client.

Lastly, these issues aren't specific to SCDF's CF-server or PCF, so I will close it. Once you have upgraded to the latest releases and if you still see problems with it, please open an issue in the [kafka-binder](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues) directly.

**Closed by sabbyanandan** 2017-11-13 17:01 UTC
