### ISSUE TITLE
Unable to remove apps due to a RDBMS Inconsistency or Deployment Event

### ISSUE THREAD

**Issue by felipeg48** [spring-cloud/spring-cloud-dataflow-server-cloudfoundry#158] opened 2016-08-11 17:46 UTC
The following notes were taking to debug an error when destroying streams. The SCDF Server was unable to remove destroy the apps.

**Using**:
- PCFDev (the latest)
 - API: api.local.pcfdev.io
 - Domain: local.pcfdev.io

**To reproduce the error:**

1. Create the Services (redis,rabbit,mysql)
2. Create a manifest.yml that contains all the ENV variables need.
 - Put a BAD URL in the SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_DOMAIN
3. Deploy the Server with `cf push`
4. Start the Data Shell
5. Connect to the server: `dataflow config server http://dataflow-server.local.pcfdev.io`
4. Import the apps: `app import --uri http://bit.ly/stream-applications-rabbit-maven`
5. Create a stream: `stream create --name myfilter --definition "http | filter  --expression=#jsonPath(payload,'$.origin.countryCode').equals('US') | log"`
6. Deploy the stream: `stream deploy myfilter`

**What happen?**

**A) dataflow-server logs:** 
o.s.c.d.s.c.CloudFoundryAppDeployer      : Error creating app dataflow-hydraemic-strigil-myfilter-log
java.lang.IllegalStateException: Domain local.pcfdev.io not found

**B) Doing:**
```
$ cf apps

Getting apps in org pcfdev-org / space pcfdev-space as admin...
OK

name                                                      requested state   instances   memory   disk   urls
dataflow-server                                           started           1/1         1G       512M   dataflow-server.local.pcfdev.io
dataflow-fastidious-resorcinolphthalein-myfilter-log      stopped           0/1         512M     512M
dataflow-fastidious-resorcinolphthalein-myfilter-filter   stopped           0/1         512M     512M
dataflow-fastidious-resorcinolphthalein-myfilter-http     stopped           0/1         512M     512M
```

Looking at the MySQL: 

```
mysql> select * from DEPLOYMENT_IDS;
+-----------------+---------------------------------------------------------+
| DEPLOYMENT_KEY  | DEPLOYMENT_ID                                           |
+-----------------+---------------------------------------------------------+
| myfilter.filter | dataflow-fastidious-resorcinolphthalein-myfilter-filter |
| myfilter.http   | dataflow-fastidious-resorcinolphthalein-myfilter-http   |
| myfilter.log    | dataflow-fastidious-resorcinolphthalein-myfilter-log    |
+-----------------+---------------------------------------------------------+
```

Taking a look at the streams:

```
╔═══════════╤════════════════════════════════════════════════════════════════════════════════════════╤══════════╗
║Stream Name│                                   Stream Definition                                    │  Status  ║
╠═══════════╪════════════════════════════════════════════════════════════════════════════════════════╪══════════╣
║myfilter   │http | filter  --expression=#jsonPath(payload,'$.origin.countryCode').equals('US') | log│undeployed║
╚═══════════╧════════════════════════════════════════════════════════════════════════════════════════╧══════════╝
```

**NOTES:** 'Do not destroy the stream'

**Next:**

7. Fix the SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_DOMAIN in the manifest.yml
8. Do a `cf push`
9. Re-deploy the stream: `stream deploy myfilter`

**What happen:**

**A) dataflow-server logs:**

Unique index or primary key violation: "PRIMARY_KEY_D ON PUBLIC.DEPLOYMENT_IDS(DEPLOYMENT_KEY) VALUES ('myfilter.http', 7)"; SQL statement:
INSERT into DEPLOYMENT_IDS (DEPLOYMENT_KEY, DEPLOYMENT_ID)values (?, ?) [23505-191]
Unique index or primary key violation: "PRIMARY_KEY_D ON PUBLIC.DEPLOYMENT_IDS(DEPLOYMENT_KEY) VALUES ('myfilter.log', 7)"; SQL statement:
INSERT into DEPLOYMENT_IDS (DEPLOYMENT_KEY, DEPLOYMENT_ID)values (?, ?) [23505-191]
Unique index or primary key violation: "PRIMARY_KEY_D ON PUBLIC.DEPLOYMENT_IDS(DEPLOYMENT_KEY) VALUES ('myfilter.filter', 7)"; SQL statement:
INSERT into DEPLOYMENT_IDS (DEPLOYMENT_KEY, DEPLOYMENT_ID)values (?, ?) [23505-191]

**B) Doing:**

```
$ cf apps

Getting apps in org pcfdev-org / space pcfdev-space as admin...
OK

name                                                      requested state   instances   memory   disk   urls
dataflow-server                                           started           1/1         1G       512M   dataflow-server.local.pcfdev.io
dataflow-fastidious-resorcinolphthalein-myfilter-log      stopped           0/1         512M     512M
dataflow-fastidious-resorcinolphthalein-myfilter-filter   stopped           0/1         512M     512M
dataflow-fastidious-resorcinolphthalein-myfilter-http     stopped           0/1         512M     512M
dataflow-undoctored-nullah-myfilter-log                   started           1/1         512M     512M   dataflow-undoctored-nullah-myfilter-log.local.pcfdev.io
dataflow-undoctored-nullah-myfilter-filter                started           1/1         512M     512M   dataflow-undoctored-nullah-myfilter-filter.local.pcfdev.io
dataflow-undoctored-nullah-myfilter-http                  started           1/1         512M     512M   dataflow-undoctored-nullah-myfilter-http.local.pcfdev.io
```

Looking at the MySQL: 

```
mysql> select * from DEPLOYMENT_IDS;
+-----------------+---------------------------------------------------------+
| DEPLOYMENT_KEY  | DEPLOYMENT_ID                                           |
+-----------------+---------------------------------------------------------+
| myfilter.filter | dataflow-fastidious-resorcinolphthalein-myfilter-filter |
| myfilter.http   | dataflow-fastidious-resorcinolphthalein-myfilter-http   |
| myfilter.log    | dataflow-fastidious-resorcinolphthalein-myfilter-log    |
+-----------------+---------------------------------------------------------+
3 rows in set (0.00 sec)
```

Still keeps the previous records due the SQL Exception about the PRIMARY_KEY VIOLATION

Taking a look at the streams:

```
╔═══════════╤════════════════════════════════════════════════════════════════════════════════════════╤══════════╗
║Stream Name│                                   Stream Definition                                    │  Status  ║
╠═══════════╪════════════════════════════════════════════════════════════════════════════════════════╪══════════╣
║myfilter   │http | filter  --expression=#jsonPath(payload,'$.origin.countryCode').equals('US') | log│undeployed║
╚═══════════╧════════════════════════════════════════════════════════════════════════════════════════╧══════════╝
```

If I post some data:

```
dataflow:>http post --target http://dataflow-undoctored-nullah-myfilter-http.local.pcfdev.io --data "{'origin': {'id':3374, 'countryCode': 'US'}}"
> POST (text/plain;Charset=UTF-8) http://dataflow-undoctored-nullah-myfilter-http.local.pcfdev.io {'origin': {'id':3374, 'countryCode': 'US'}}
> 202 ACCEPTED
```

and seeing the logs:

```
$ cf logs dataflow-undoctored-nullah-myfilter-log   

2016-08-11T10:37:03.44-0600 [APP/0]      OUT 2016-08-11 16:37:03.448  INFO 18 --- [lter.myfilter-1] log.sink  : {'origin': {'id':3374, 'countryCode': 'US'}}
2016-08-11T10:39:36.25-0600 [APP/0]      OUT 2016-08-11 16:39:36.256  INFO 18 --- [lter.myfilter-1] log.sink  : {'origin': {'id':3374, 'countryCode': 'US'}}

```

It worked.

**Next**

10. Destroying the Stream:

```
dataflow:>stream list
╔═══════════╤═════════════════╤══════╗
║Stream Name│Stream Definition│Status║
╚═══════════╧═════════════════╧══════╝
```

**What happen?**

**A) Doing:**

```
mysql> select * from DEPLOYMENT_IDS;
Empty set (0.00 sec)
```

and reviews the apps:

```
$ cf apps

Getting apps in org pcfdev-org / space pcfdev-space as admin...
OK

name                                                      requested state   instances   memory   disk   urls
dataflow-server                                           started           1/1         1G       512M   dataflow-server.local.pcfdev.io
dataflow-fastidious-resorcinolphthalein-myfilter-log      stopped           0/1         512M     512M
dataflow-fastidious-resorcinolphthalein-myfilter-filter   stopped           0/1         512M     512M
dataflow-fastidious-resorcinolphthalein-myfilter-http     stopped           0/1         512M     512M
dataflow-undoctored-nullah-myfilter-log                   started           1/1         512M     512M   dataflow-undoctored-nullah-myfilter-log.local.pcfdev.io
dataflow-undoctored-nullah-myfilter-filter                started           1/1         512M     512M   dataflow-undoctored-nullah-myfilter-filter.local.pcfdev.io
dataflow-undoctored-nullah-myfilter-http                  started           1/1         512M     512M   dataflow-undoctored-nullah-myfilter-http.local.pcfdev.io
```

**My Notes:**

Even so, the SQL is gone, now there is an inconsistency and all the applications should be removed.
Now, probabnly you are thinking that I should destroyed the stream since the first time, but I know that my stream is correct, so that's why I didn't delete it.

I reviewed the code, specifically in the **org.springframework.cloud.dataflow.server.controller.StreamDeploymentController.java** around lines: 249-250 in the **deployStream** method.

```java
			try {
				String id = this.deployer.deploy(request);
				this.deploymentIdRepository.save(DeploymentKey.forStreamAppDefinition(currentApp), id);
			}
			// If the deployer implementation handles the deployment request synchronously, log warning message if
			// any exception is thrown out of the deployment and proceed to the next deployment.
			catch (Exception e) {
				loggger.warn(String.format("Exception when deploying the app %s: %s", currentApp, e.getMessage()));
			}
```

My Notes:

Probably in the app deployment (cf-java-client) there is not event propagation for an error(that's why even it failed to deploy, the apps are created anyway, leaving them in bad state), also these apps keys are being persisted as well.

What would be the use case here if this happen?

**Comment by ericbottard** [comment] 2016-08-16 10:34
Tried to reproduce a similar situation on CF.
I'm a bit confused that you can see the apps the first time, even though the domain was wrong; How did the server/deployer know how to create them then?

Not regarding that point, I believe the issue is that you should have `undeployed` the streams before trying to deploy them again. That the server did not force you to do that (or did its bookkeeping internally correctly) is the real issue here.

**Comment by felipeg48** [comment] 2016-08-16 22:53
My case here, is that by viewing the Logs (first time) and seeing that the apps weren't deployed due the BAD domain, I assumed that my stream was correct, so no need to destroy it, just re-stage the dataflow-server with the correct URL domain.

I think the deployment of the apps when an error occurs, should trigger something: 
a) Remove the apps that are already kind in bad state
b) Try not to persist some of the keys,
so the next time you execute the deploy, it won't be any issue about keys or more than one app hanging.

Of course this was probably not the way to do things, but let imagine that we have all the environment variables set with the correct value. What will happen when an app won't start due something else (memory, disk, any service attached, etc), I think it would produce the same error, it would create the apps in CF and when you re-deploy it will create another set of apps and so on.

**Comment by sabbyanandan** [comment] 2016-08-25 15:05
This is still not reproducible. @felipeg48: Could you verify this on [1.0.0.RC1](http://repo.spring.io/libs-milestone/org/springframework/cloud/spring-cloud-dataflow-server-cloudfoundry/1.0.0.RC1/)?

**Comment by felipeg48** [comment] 2016-08-26 16:11
Yes, I'll test it today and I'll send my feedback, thanks Sabby

**Comment by sabbyanandan** [comment] 2016-10-16 18:39
@felipeg48: If you're still facing issues, please reopen it. I will close it for now.

**Closed by sabbyanandan** 2016-10-16 18:39 UTC
Labels: bug, next iteration
