### ISSUE TITLE
OutOfDirectMemoryError during Stream deployment on PCF

### ISSUE THREAD

**Issue by rahulvijay24feb** [spring-cloud/spring-cloud-dataflow-server-cloudfoundry#360] opened 2017-10-09 04:26 UTC
Spring cloud data flow server throws the  below error in logs while trying to do stream deployment. Scaling up dataflow server to 2gb memory  and disk shows no resolution. Version being used  - 1.3.0 snapshot. 
Log:

2017-10-08T23:35:23.909-04:00 [APP/PROC/WEB/0] [OUT] 2017-10-09 03:35:23.908 WARN 20 --- [ry-client-nio-3] i.n.c.AbstractChannelHandlerContext : An exception '{}' [enable DEBUG level for full stacktrace] was thrown by a user handler's exceptionCaught() method while handling the following exception:
2017-10-08T23:35:23.909-04:00 [APP/PROC/WEB/0] [OUT] io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 16921 byte(s) of direct memory (used: 10474106, max: 10485760)
2017-10-08T23:35:23.909-04:00 [APP/PROC/WEB/0] [OUT] at io.netty.util.internal.PlatformDependent.incrementMemoryCounter(PlatformDependent.java:585) ~[netty-common-4.1.9.Final.jar!/:4.1.9.Final]
2017-10-08T23:35:23.909-04:00 [APP/PROC/WEB/0] [OUT] at io.netty.util.internal.PlatformDependent.allocateDirectNoCleaner(PlatformDependent.java:539) ~[netty-common-4.1.9.Final.jar!/:4.1.9.Final]

**Comment by markpollack** [comment] 2017-10-09 13:20
Hi.
What version of PCF are you using and what buildback is being used to deploy the SCDF server?

**Comment by sabbyanandan** [comment] 2017-10-09 13:21
Hi, @rahulvijay24feb. Could you confirm the release versions of Java-Buildpack, SCDF and PCF? When it comes to posts like this, it is always helpful to have as many details as possible - see here for more [information](https://github.com/spring-cloud/spring-cloud-dataflow/wiki/Reporting-Issues).

**Comment by rahulvijay24feb** [comment] 2017-10-10 14:06
Hello, Please find the details below
Deployment Environment : PCF
PCF Version : 12.1.0
SCDF Server : 1.3.0.BUILD-SNAPSHOT
SCDF Shell : 1.3.0.M2
Buildpack : https://github.com/cloudfoundry/java-buildpack

**Comment by sabbyanandan** [comment] 2017-10-10 14:40
You mean, PCF 1.12? Also, what is that you're trying in SCDF? Can you share your stream/task definitions? It'd be useful to also review your `manifest.yml` (without user/pass creds, of couse).

**Comment by rahulvijay24feb** [comment] 2017-10-10 14:53
Manifest for SCDF server :
instances: 1
memory: 1G
applications:
  - name: iordfserver_pt
    path: spring-cloud-dataflow-server-cloudfoundry-1.3.0.BUILD-SNAPSHOT.jar
    buildpack: https://github.com/cloudfoundry/java-buildpack  
    services:
      - MySQL
      - RABBITMQ
      - REDIS
    env:
      SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_URL : https://api.sys.XXX.pcf.XXX.com
      SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_ORG : ORG
      SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_SPACE : DEV
      SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_DOMAIN : XXX.pcf.XXX.com
      SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_SERVICES : RABBITMQ
      SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_USERNAME : XXXXX
      SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_PASSWORD : XXXXXX
      SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_SKIP_SSL_VALIDATION : false
      SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_STREAM_ENABLE_RANDOM_APP_NAME_PREFIX : false
      SPRING_CLOUD_DATAFLOW_SERVER_CLOUDFOUNDRY_FREE_DISK_SPACE_PERCENTAGE : 25

---------------- End of Manifest ----------------------------

Stream definition consists for two custom stream apps  di (Source), ds (Sink).

stream create --definition "di| ds" --name "datastream"
stream deploy --name "datastream"

**Comment by sabbyanandan** [comment] 2017-10-10 15:06
One other thing. Is PCF 1.12 running on GCP? If not, which IaaS is in use?

**Comment by sabbyanandan** [comment] 2017-10-10 17:29
@rahulvijay24feb: FWIW, our e2e acceptance of `1.3.0.BUILD-SNAPSHOT` on PCF 1.12 running on vSphere and AWS are green, so we would have to understand where you're running PCF.

**Comment by rahulvijay24feb** [comment] 2017-10-10 17:29
It is running on vsphere.

**Comment by rahulvijay24feb** [comment] 2017-10-10 17:47
I tried downgrading the server as below :

SCDF server : 1.2.0.BUILD-SNAPSHOT
SCDF Shell : 1.2.0.RELEASE

With same PCF version on Vsphere.  Results return same error.


Interesting find is that with same versions of PCF and SCDF server running on Openstack, the deployment was seamless and successful .

**Comment by sabbyanandan** [comment] 2017-10-10 18:26
Please note that the latest version of java-buildpack (JBP) includes a new memory calculator and that version is set as a default in 1.12/PWS. There are no changes in SCDF specifically, but it is likely we would have to adapt to the recommended memory settings required by JBP - we are investigating it.

It is possible your Openstack environment is not using the latest JBP.

**Comment by rahulvijay24feb** [comment] 2017-10-10 20:43
I was able to successfully deploy streams by included the following JAVA OPTS for Spring Cloud Data Flow server .

JAVA_OPTS  : -XX:MaxDirectMemorySize=128M.

Looks like something was overwriting the default direct memory size from unbounded to 10MB.

**Comment by sabbyanandan** [comment] 2017-10-10 20:48
The 10MB _is the_ JBP 4.x change. It should never go over that limit; however, since `reactor-netty` is used behind the scenes, there seems to be a conflict with how netty reacts to direct-memory. We will come up with a recommended setting from our side.

**Comment by sabbyanandan** [comment] 2017-11-06 00:10
The root cause of the problem has been addressed in CFJC's 2.21.0 release. The underlying CF-deployer has been upgraded to this version via: [spring-cloud-deployer-cloudfoundry#215](https://github.com/spring-cloud/spring-cloud-deployer-cloudfoundry/issues/215). It will be released in the upcoming 1.3 milestone.

**Comment by sabbyanandan** [comment] 2017-12-12 19:33
This has been resolved in 1.3 M3 release.

**Closed by sabbyanandan** 2017-12-12 19:33 UTC
