### ISSUE TITLE
Modules should use unique routes

### ISSUE THREAD

**Issue by trisberg** [spring-cloud/spring-cloud-dataflow-server-cloudfoundry#66] opened 2016-03-03 17:10 UTC
If I deploy a `ticktock` stream the modules are deployed with non-unique routes like `http://ticktock-time.cfapps.io`. On PWS there is a strong likelihood that someone else has tried deploying `ticktock` already. We should use unique/random routes for these modules.

**Comment by ericbottard** [comment] 2016-03-03 17:29
I don't think random routes should be the only option, or even the default (I agree it should be an option). We want predictability in the urls of some of the modules. Ideally, we want better error reporting when route already taken is the error as well.
Note that this is / has been a CF issue for any tutorial from day 1

**Comment by sabbyanandan** [comment] 2016-05-09 16:08
Duplicate of spring-cloud/spring-cloud-dataflow-server-cloudfoundry#35

**Closed by sabbyanandan** 2016-05-09 16:08 UTC
Labels: enhancement
